/*Создание таблицы "Заказы"*/
USE [Orders]
GO

DROP TABLE IF EXISTS dbo.Orders
GO

CREATE TABLE Orders(
O_ID INT NOT NULL PRIMARY KEY,
O_FAMILY VARCHAR (50) NOT NULL, 
O_NAME VARCHAR (50) NOT NULL, 
O_SURNAME VARCHAR (50) NOT NULL, 
O_DATE DATE NOT NULL,
O_ADDR VARCHAR(50) NOT NULL,
O_READY DATE NOT NULL,
);
GO