/*Создание таблицы "Книги"*/
USE [Orders]
GO

DROP TABLE IF EXISTS dbo.Books
GO

CREATE TABLE Books(
B_CONTRACT INT NOT NULL PRIMARY KEY,
B_DATE DATE NOT NULL,
B_MAN INT NOT NULL FOREIGN KEY REFERENCES Employees(E_ID),
B_TITLE VARCHAR(50) NOT NULL,
B_PRICE DECIMAL(6, 2) NOT NULL,
B_ADVANCE DECIMAL(10, 2) NOT NULL,
B_FEE DECIMAL(8, 2) NOT NULL,
B_PUBL DATE NOT NULL,
B_CIRCUL INT NOT NULL,
B_EDIT INT NOT NULL FOREIGN KEY REFERENCES Employees(E_ID)
);
GO









